name: SYSTEM-DMAR
main: com.foxy.dmar.Main
version: 0.1
author: Foxy
commands:
  clearchat:
  tp:
  gmc:
  gms:
  gma:
  gmsp:
  gm:
  clear:
  kill:
  ping:
  heal:
  gamemode:
  fly:
  day:
  night:
  cc:
  tpall:
  invsee:
  dv:
  tban:
  tmute:
  baneeee:
  gban: